services:
  laravel:
    container_name: laravel
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile  # Update to the correct Dockerfile
      args:
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
    networks:
      - laravel
    ports:
      - 5173:5173
    volumes:
      - ./laravel:/var/www/app